feat(scripts): better error handling

diff --git a/scripts/folders-color-chooser b/scripts/folders-color-chooser
--- a/scripts/folders-color-chooser
+++ b/scripts/folders-color-chooser
@@ -55,18 +55,25 @@ current_color() {
 folders_color=""
 old_folders_color="$(current_color)"
 
-while getopts c:Chl-: OPT; do 
+while getopts cChl-: OPT; do 
   if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
     OPT="${OPTARG%%=*}"       # extract long option name
     OPTARG="${OPTARG#"$OPT"}" # extract long option argument (may be empty)
     OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+  else
+    OPTARG=""
   fi
   case "$OPT" in
     -)
       break ;;
     c | color)
       if [ -z "${OPTARG}" ]; then
-        shift ; folders_color="$1"
+        if [[ "$#" -gt 1 ]]; then
+          shift ; folders_color="$1"
+        else
+          echo "Missing value for '${OPT}' option. Please provide a color." >&2
+          exit 1
+        fi
       else
         folders_color="${OPTARG}"
       fi ;;
@@ -76,17 +83,22 @@ while getopts c:Chl-: OPT; do
       help
       exit ;;
     l | list)
-      echo -e "Available colors are:\n$(colors)" ; exit ;;
-    *)
-      echo "Unknown argument: $OPT" >&2 ; exit 1 ;;
+      echo "Available colors are:"
+      echo "${colors}"
+      exit ;;
     \? )
       exit 2 ;;  # bad short option (error reported via getopts)
   esac
 done
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
+if [[ "$#" -gt 0 ]]; then
+  echo "Unknown argument: $1" >&2
+  exit 1
+fi
+
 if [[ ! -d "$(icon_pack_path)" ]]; then
-  echo "Icon pack path not found. Abort."
+  echo "Icon pack path not found. Abort." >&2
   exit 1
 fi
 
