feat(scripts): remove icon pack theme option

diff --git a/scripts/folders-color-chooser b/scripts/folders-color-chooser
--- a/scripts/folders-color-chooser
+++ b/scripts/folders-color-chooser
@@ -2,24 +2,43 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-export ICON_PACK_THEME="${ICON_PACK_THEME:-"Gruvbox-Plus-Dark"}"
+colors="black blue citron firebrick gold green grey highland jade lavender lime olive orange pistachio plasma pumpkin purple red rust sapphire tomato violet white yellow"
+default_color="plasma"
+icon_pack_theme="Gruvbox-Plus-Dark"
+
+help() {
+  echo -e "Folders color chooser
+
+Current color: $(current_color)
+
+Usage:
+  ${0##*/} [-c | --color=<color>] [-C | --reset-color]
+  ${0##*/} [-h | --help]
+  ${0##*/} [-l | --list]
+
+Options:
+  -c, --color=<color>   set the new folders color
+  -C, --reset-color     reset folder color to ${default_color}
+  -h, --help            show this help
+  -l, --list            list available colors"
+}
 
 # Browse icons directories in this order:
 # - $XDG_DATA_HOME/icons (defaults to $HOME/.local/share/icons)
 # - $HOME/.icons (for backwards compatibility)
 # - $XDG_DATA_DIRS/icons (defaults to /usr/local/share/icons:/usr/share/icons)
 icon_pack_path() {
-  if [[ -d "${XDG_DATA_HOME:-"${HOME}/.local/share"}/icons/${ICON_PACK_THEME}" ]]; then
-    echo "${XDG_DATA_HOME:-"${HOME}/.local/share"}/icons/${ICON_PACK_THEME}"
+  if [[ -d "${XDG_DATA_HOME:-"${HOME}/.local/share"}/icons/${icon_pack_theme}" ]]; then
+    echo "${XDG_DATA_HOME:-"${HOME}/.local/share"}/icons/${icon_pack_theme}"
     return 0
-  elif [[ -d "${HOME}/.icons/${ICON_PACK_THEME}" ]]; then
-    echo "${HOME}/.icons/${ICON_PACK_THEME}"
+  elif [[ -d "${HOME}/.icons/${icon_pack_theme}" ]]; then
+    echo "${HOME}/.icons/${icon_pack_theme}"
     return 0
   else
     data_dirs=$(echo "${XDG_DATA_DIRS:-"/usr/local/share:/usr/share"}" | tr ":" "\n")
     for path in $data_dirs; do
-      if [[ -d "${path%%/}/icons/${ICON_PACK_THEME}" ]]; then
-        echo "${path%%/}/icons/${ICON_PACK_THEME}"
+      if [[ -d "${path%%/}/icons/${icon_pack_theme}" ]]; then
+        echo "${path%%/}/icons/${icon_pack_theme}"
         return 0
       fi
     done
@@ -27,44 +46,14 @@ icon_pack_path() {
   return 1
 }
 
-if [[ ! -d "$(icon_pack_path)" ]]; then
-  echo "Icon pack path not found. Abort."
-  exit 1
-fi
-
 scalable_places_directory="$(icon_pack_path)/places/scalable"
-
-if [[ ! -d "${scalable_places_directory}" ]]; then
-  echo "Folder icons not found. Abort."
-  exit 1
-fi
-
-colors="black blue citron firebrick gold green grey highland jade lavender lime olive orange pistachio plasma pumpkin purple red rust sapphire tomato violet white yellow"
 
 current_color() {
   readlink "${scalable_places_directory}/folder.svg" | cut --delimiter "-" --fields 2 | cut --delimiter "." --fields 1
 }
 
-default_color="plasma"
 folders_color=""
 old_folders_color="$(current_color)"
-
-help="Folders color chooser
-
-Icon pack path: $(icon_pack_path)
-
-Current color: $(current_color)
-
-Usage: ${0##*/} [-c | --color=<color>] [-C | --reset-color] [-h | --help] [-l | --list]
-
-Environment:
-  ICON_PACK_THEME   name of the Gruvbox Plus icon pack (default: Gruvbox-Plus-Dark)
-
-Options:
-  -c, --color=<color>   set the new folders color
-  -C, --reset-color     reset folder color to ${default_color}
-  -h, --help            show this help
-  -l, --list            list available colors"
 
 while getopts c:Chl-: OPT; do 
   if [ "$OPT" = "-" ]; then   # long option: reformulate OPT and OPTARG
@@ -84,7 +73,7 @@ while getopts c:Chl-: OPT; do
     C | reset-color)
       folders_color="${default_color}" ;;
     h | help)
-      echo -e "${help}"
+      help
       exit ;;
     l | list)
       echo -e "Available colors are:\n$(colors)" ; exit ;;
@@ -96,8 +85,18 @@ while getopts c:Chl-: OPT; do
 done
 shift $((OPTIND-1)) # remove parsed options and args from $@ list
 
+if [[ ! -d "$(icon_pack_path)" ]]; then
+  echo "Icon pack path not found. Abort."
+  exit 1
+fi
+
+if [[ ! -d "${scalable_places_directory}" ]]; then
+  echo "Folder icons not found. Abort."
+  exit 1
+fi
+
 if [[ -z "${folders_color}" ]]; then
-  echo -e "${help}"
+  help
   exit
 fi
 
